### ISSUE TITLE
Add HTML doctype and charset tags

### ISSUE THREAD

**Issue by FrameXX** [smalljustin/little-guys#1]
You are missing doctype and charset tags in your index.html page.
This will make most modern browsers freak out although in your case it may not cause too much trouble with the game.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default#how_do_browsers_determine_which_mode_to_use).

![image](https://github.com/user-attachments/assets/449295ca-b03e-4e02-8bb9-2bbedcb700c2)

**Comment by smalljustin** [comment]
Thanks, added
